### ISSUE TITLE
[Feature] The opportunity to make a (line-)break with a cup of tea 

### ISSUE THREAD

**Issue by nikmel2803** [jevakallio/css-properly#4]
In English css, I suggest using `tea` instead of `;` to make line breakes more pleasent
Smth like this: 
```css
.foo {
  colour: black tea
  background-colour: lightgrey tea
  text-align: centre tea
}
```
